name: CI/CD Development
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: auto deploy
    runs-on: ubuntu-latest

    steps:
    - name: get latest code
      uses: actions/checkout@v3
      continue-on-error: false

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.0.0
      with:
        server: hireme.kaitodecode.com
        username: school@hireme.kaitodecode.com
        password: ER8l23YowU7wi
        port: 21
        protocol: ftp
        exclude: |
          */.git
          */.git/**
          */node_modules/*
          */vendor/*
          */storage/imports/*
      continue-on-error: true

